minio:
  endpoint: http://minio.ouest.innovation.insee.eu
  db_settings_file: s3://ssplab/aiee2/data/settings.yml

files:
  - rp_final_2014:
    minio_url: s3://ssplab/aiee2/data/hackaton/rp_final_2014.csv
    table_name: rp_final_2014
    typage_file: typage_rp.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~' 
    
  - rp_final_2017:
    minio_url: s3://ssplab/aiee2/data/hackaton/rp_final_2017.csv
    table_name: rp_final_2017
    typage_file: typage_rp.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~' 

  - rp_final_2018:
    minio_url: s3://ssplab/aiee2/data/RP/bdd18.csv
    table_name: rp_final_2018
    typage_file: typage_rp.csv
    options_csv_dta:
      separator_csv: ',' 
      separator_buffer: '~'

  - rp_final_2019:
    minio_url: s3://ssplab/aiee2/data/RP/bdd19.csv
    table_name: rp_final_2019
    typage_file: typage_rp.csv
    options_csv_dta:
      separator_csv: ',' 
      separator_buffer: '~'
      
  - rp_final_2020:
    minio_url: s3://ssplab/aiee2/data/RP/ear2020_dep14_dep63.csv
    table_name: rp3.individus
    typage_file: typage_rp2020.csv
    options_csv_dta:
      separator_csv: ',' 
      separator_buffer: '~'

  - sirus_2014:
    minio_url: s3://ssplab/aiee2/data/hackaton/sirus_2014.csv
    table_name: sirus_2014
    typage_file: typage_sirus.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~'
      
  - sirus_2017:
    minio_url: s3://ssplab/aiee2/data/hackaton/sirus_2017.csv
    table_name: sirus_2017
    typage_file: typage_sirus.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~'
    
  - sirus_2018:
    minio_url: s3://ssplab/aiee2/data/Sirus/sirus18.csv
    table_name: sirus_2018
    typage_file: typage_sirus.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~'
      
  - sirus_2019:
    minio_url: s3://ssplab/aiee2/data/Sirus/sirus19.csv
    table_name: sirus_2019
    typage_file: typage_sirus.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~'

  - sirus_2020:
    minio_url: s3://ssplab/aiee2/data/Sirus/sirus20.csv
    table_name: sirus_2020
    typage_file: typage_sirus_noxy.csv
    options_csv_dta:
      separator_csv: ';' 
      separator_buffer: '~'