#no smote
minio:
  endpoint: http://minio.ouest.innovation.insee.eu
  
import_data_sql: "SELECT *, 0 as blank FROM  sirus_2019 s LEFT JOIN modalites m ON s.apet = m.code LIMIT 100000000 "
prediction_mode: False
path_output: "output"
cols_id:
    - "sirus_id"
    - "nic"
cleaners:
    - clean1: 
        type: "CleanerRemoveSpecialChar"
        cols: 
                - "blank"
                - "denom"
                - "libelle"
                - "blank"
                - "adr_et_l6"
                - "adr_et_post"
                - "adr_et_l1"
                - "adr_et_l2"
    - clean2: 
        type: "CleanerAdrCltX"
        cols: 
                - "blank"
                - "denom"
                - "libelle"
                - "blank"
                - "adr_et_l6"
                - "adr_et_post"
                - "adr_et_l1"
                - "adr_et_l2"
    - clean3: 
        type: "CleanerAdrDltX"
        cols: 
                - "blank"
                - "denom"
                - "libelle"
                - "blank"
                - "adr_et_l6"
                - "adr_et_post"
                - "adr_et_l1"
                - "adr_et_l2"
processes: 
    - tr1:
        type: "ProcessMLPSiamese"
        param:
            fasttext: False
            fasttext_size: 120
            ngram: "3"
            list_cols: 
                fusion_si:
                    - "denom"
                    - "libelle"
                    - "blank"
                    - "adr_et_l6"
                    - "adr_et_post"
                    - "adr_et_l1"
                    - "adr_et_l2"
echantillon: []
models:     
  - model1:
        type: "MLPSimilarity"
        param:  
            fasttext: False
            embedding_size: 120
            nb_blocks: 1
            nb_heads: 3
            ff_dim: 64
            denses_sizes: [128]
              