#no smote
minio:
  endpoint: http://minio.ouest.innovation.insee.eu
  bucket: ssplab/aiee2/
  
import_data_sql: "SELECT *, null as blank FROM rp_final_2019 r INNER JOIN sirus_2019 s ON (LEFT(r.siretc,9) = s.sirus_id  AND s.nic = RIGHT(r.siretc, 5)) LEFT JOIN bi_lot_2019 b ON r.cabbi = b.cabbi LEFT JOIN modalites m ON s.apet = m.code LIMIT 10000"
prediction_mode: False

cleaners:
    - clean4: 
        type: "CleanerConcat_profs"
        cols: 
            - "blank"
            - "rs_x"
            - "clt_x"
            - "profs_x"
            - "profi_x"
            - "profa_x"
            - "actet_x"
            - "dlt_x"
            - "plt_x"
            - "denom"
            - "libelle"
            - "blank"
            - "adr_et_l6"
            - "adr_et_post"
            - "adr_et_l1"
            - "adr_et_l2"
            - "vague_id"
            - "lot_id"
            - "siretc"
            - "cabbi"
    - clean1: 
        type: "CleanerRemoveSpecialChar"
        cols: 
            - "blank"
            - "rs_x"
            - "clt_x"
            - "profs_x"
            - "profi_x"
            - "profa_x"
            - "actet_x"
            - "dlt_x"
            - "plt_x"
            - "denom"
            - "libelle"
            - "blank"
            - "adr_et_l6"
            - "adr_et_post"
            - "adr_et_l1"
            - "adr_et_l2"
            - "vague_id"
            - "lot_id"
            - "siretc"
            - "cabbi"
    - clean2: 
        type: "CleanerAdrCltX"
        cols: 
            - "blank"
            - "rs_x"
            - "clt_x"
            - "profs_x"
            - "profi_x"
            - "actet_x"
            - "dlt_x"
            - "plt_x"
            - "denom"
            - "libelle"
            - "blank"
            - "adr_et_l6"
            - "adr_et_post"
            - "adr_et_l1"
            - "adr_et_l2"
            - "vague_id"
            - "lot_id"
            - "siretc"
            - "cabbi"
    - clean3: 
        type: "CleanerAdrDltX"
        cols: 
            - "blank"
            - "rs_x"
            - "clt_x"
            - "profs_x"
            - "profi_x"
            - "profa_x"
            - "actet_x"
            - "dlt_x"
            - "plt_x"
            - "denom"
            - "libelle"
            - "blank"
            - "adr_et_l6"
            - "adr_et_post"
            - "adr_et_l1"
            - "adr_et_l2"
            - "vague_id"
            - "lot_id"
            - "siretc"
            - "cabbi"           
processes: 
    - tr1:
        type: "ProcessMLPSiamese"
        param:
            fasttext: False
            fasttext_size: 120
            ngram: "3"
            list_cols: 
                fusion_bi:
                    - "rs_x"
                    - "actet_x"
                    - "profs_x"
                    - "clt_x"
                    - "dlt_x"
                fusion_si:
                    - "denom"
                    - "libelle"
                    - "blank"
                    - "adr_et_l6"
                    - "adr_et_post"
                    - "adr_et_l1"
                    - "adr_et_l2"
echantillon: []
models:      
    - model1:
        type: "MLPSimilarity"
        param:  
            fasttext: False
            embedding_size: 120
            nb_blocks: 1
            nb_heads: 3
            ff_dim: 64
            denses_sizes: [128]
        training:
            batch_size: 32
            nb_epochs: 10
              