#no smote
minio:
  endpoint: http://minio.ouest.innovation.insee.eu
  trainings_dir: s3://ssplab/aiee2/nomenclatures
  sync: True
local:
  trainings_dir: trainings
data:
  cleaner_class: ProfCleaner
  force_generation: False
  postgres_sql: 'SELECT rp_final_2017.cabbi, rs_x, actet_x, profi_x, profs_x, profa_x, profi_c, profs_c, profa_c FROM rp_final_2017 INNER JOIN profession_2017 ON rp_final_2017.cabbi = profession_2017.cabbi WHERE ((profa_x IS NOT NULL) OR (profs_x IS NOT NULL) OR (profi_x IS NOT NULL))'
  limit_nb_doc: null
  nomenclature:
    name: PCS
    topcode: PCS1
    node_dist_top_to_first_cat: 1
  use_stemmer: True
  ngrams:
    use: False
    ngrams_size: 2
  fasttext:
    use: True
    remote_directory: 'fasttext'
    embedding_size: 210
    trainable: True
trainings:         
  model: TransformerModel
  data:
    gt_column : prof_c
    input_columns: ['prof_repr', 'rs_repr', 'actet_repr']
  model_params: 
    seq_len: 20
    embedding_size: 210
    nb_blocks: 1
    nb_heads: 3
    ff_dim: 64
    dropout: 0.1
    dense_sizes: [128]
  training_params:
    batch_size: 10
    nb_epochs: 5
post_process:
  top_X_to_optimize: 5
  nb_trials: 50
  optim_timeout_in_min: 1800
  alpha_tree_mod: 0
  beta_str_sim_mod: 0
top1_classifier:
  metric_to_maximize: 'precision'
  save_file: ""
  threshold: 0.5
